# vim: sts=2 ts=2 sw=2 et ai

docker:
  process_signature: '/usr/bin/docker'
  python_pip_package: 'python-pip'
  install_docker_py: False
  refresh_repo: True
  config: []

  pip:
    upgrade: False
    version: 9.0.1

  use_upstream_repo: True
  compose_version: 1.21.0

  containers:
    skip_translate: None
    force_present: False
    force_running: False
